### ISSUE TITLE
Highlight the merger border when child input get focused

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-input-merger-changelog#1]
when clicked, the inner input will get focused, but not the div.input-merger.form-control

Component link: https://codyhouse.co/ds/components/app/input-merger

**Comment by sebastiano-guerriero** [comment]
please refer to the info page for more info about how to extend the focus effect:
https://codyhouse.co/ds/components/info/input-merger

We couldn't include it in the demo because our users can modify the form elements using the form editor.
